### ISSUE TITLE
Getting error "system cannot find the file specified"

### ISSUE THREAD

**Issue by a-ssassi-n** [sensei-z/Edit_AAB#2]
While running the application on Windows 10, I am getting this error:

**Screenshot:**
![image](https://user-images.githubusercontent.com/7111734/140636040-69cae994-fa9a-4d8e-84e8-b4d6c28f1d95.png)

===

Java 8 Installed
.Net core 3.1 installed
.Net runtime 3.1 installed
Python 3.10 installed

===

**EDIT:**  Looks like the application is configured/compiled to get the files your system specified path because I can see your PC username "**amd**" on the error.

**Comment by a-ssassi-n** [comment]
I installed Python from Windows Store and the issue was solved.

**Comment by sensei-z** [comment]
> I installed Python from Windows Store and the issue was solved.

basically it check all requirement on start up if requirement are not installed it show error  and requirements are already mentioned
![image](https://user-images.githubusercontent.com/89777396/140644854-cfdb22c3-17ee-43a3-8114-b11b0b76bf7a.png)
