### ISSUE TITLE
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.

### ISSUE THREAD

**Issue by 301eftekhari** [sensei-z/Edit_AAB#3]
When i run app, this error dialog show:

> ---------------------------
> Error
> ---------------------------
> error:System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
> 
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
> 
>    at System.Diagnostics.Process.Start()
> 
>    at AAB_Studio.MainWindow.pip() in C:\Users\amd\source\repos\AAB Studio\AAB Studio\MainWindow.xaml.cs:line 181
> ---------------------------
> OK   
> ---------------------------

**Comment by sensei-z** [comment]
You need to setup the pip  in environment variables 

use python latest version
